name = input("Who are u?")
city = input('where do you live?')
age = input('how old are you?')
hobby = input('what is your hobby?')
movie = input('what is your favorite movie?')
food = input('what is your favorite food?')

print("-------YOUR DETAILS FILLED BY YOU-------")
print("Name:", name)
print("City:", city)
print("Age:", age)
print("Hobby:", hobby)
print("Movie:", movie)
print("Food:", food)
print("----THE END----")